#include "Localization.hpp"

#include <atomic>
#include <string>
#include <string_view>
#include <unordered_map>

namespace localization {
namespace {

using namespace std::literals;

std::atomic<Language> g_language{Language::ZH_CN};

const std::unordered_map<std::string_view, std::string_view> ZH_CN{
    {"About"sv, "关于"sv},
    {"UEVR Roco Kingdom MorefunUE4 Compatibility Edition | Compatibility adaptation & Chinese localization: sicuncat/偏差"sv, "UEVR洛克王国 MorefunUE4 兼容版 | 兼容适配与中文维护：sicuncat/偏差"sv},
    {"FrameworkConfig"sv, "框架设置"sv},
    {"Main"sv, "主要设置"sv},
    {"GUI/Themes"sv, "界面/主题"sv},
    {"VR"sv, "VR"sv},
    {"Runtime"sv, "运行时"sv},
    {"Unreal"sv, "虚幻引擎"sv},
    {"Input"sv, "输入"sv},
    {"Camera"sv, "相机"sv},
    {"Keybinds"sv, "按键绑定"sv},
    {"Console/CVars"sv, "控制台/CVar"sv},
    {"Compatibility"sv, "兼容性"sv},
    {"Debug"sv, "调试"sv},
    {"UObjectHook"sv, "UObject Hook"sv},
    {"Config"sv, "配置"sv},
    {"Developer"sv, "开发者"sv},
    {"PluginLoader"sv, "插件加载器"sv},
    {"LuaLoader"sv, "Lua 加载器"sv},
    {"Script UI"sv, "脚本界面"sv},
    {"Language"sv, "语言"sv},
    {"简体中文"sv, "简体中文"sv},
    {"Transparency"sv, "透明效果"sv},
    {"Input Passthrough"sv, "输入穿透"sv},
    {"Show Advanced Options"sv, "显示高级选项"sv},
    {"Reset to Default Settings"sv, "恢复默认设置"sv},
    {"Keyboard Menu Key: Insert"sv, "键盘菜单键：Insert"sv},
    {"Gamepad L3 + R3: Toggle Menu"sv, "手柄 L3 + R3：开关菜单"sv},
    {"Gamepad RT: Shortcuts"sv, "手柄 RT：快捷操作"sv},
    {"Gamepad LB/RB: Change Sidebar Page"sv, "手柄 LB/RB：切换侧栏页面"sv},
    {"Makes the UI transparent when not focused."sv, "界面未获得焦点时自动变为透明。"sv},
    {"Allows mouse and keyboard inputs to register to the game while the UI is focused."sv, "界面获得焦点时，仍将鼠标和键盘输入传递给游戏。"sv},
    {"Show additional options for greater control over various settings."sv, "显示更多选项，以便精细调整各项设置。"sv},
    {"Framework is currently initializing..."sv, "框架正在初始化……"sv},
    {"This menu will close after initialization if you have the remember option enabled."sv, "如果启用了记忆菜单状态，初始化完成后此菜单将自动关闭。"sv},
    {"Framework error: %s"sv, "框架错误：%s"sv},
    {"UEVR original author: praydog"sv, "UEVR 原作者：praydog"sv},
    {"Compatibility adaptation and Chinese localization: sicuncat/偏差"sv, "兼容适配与中文维护：sicuncat/偏差"sv},
    {"Unofficial community compatibility project; not affiliated with or endorsed by upstream authors or game rights holders."sv, "非官方社区兼容项目，与上游作者及游戏权利方无隶属或背书关系。"sv},
    {"Unreal Engine VR"sv, "虚幻引擎 VR"sv},
    {"Branch: %s"sv, "分支：%s"sv},
    {"Commits: %i"sv, "提交数：%i"sv},
    {"Commit hash: %s"sv, "提交哈希：%s"sv},
    {"Tag: %s"sv, "标签：%s"sv},
    {"Commits past tag: %i"sv, "标签后的提交数：%i"sv},
    {"Build date: %s"sv, "构建日期：%s"sv},
    {"Build time: %s"sv, "构建时间：%s"sv},
    {"Licenses"sv, "许可证"sv},
    {"Reset to default"sv, "恢复默认值"sv},
    {"Press any key..."sv, "请按任意键……"sv},
    {"%i (Unknown)"sv, "%i（未知）"sv},
    {"Not bound"sv, "未绑定"sv},
    {"Menu Key"sv, "菜单按键"sv},
    {"Show Cursor Key"sv, "显示光标按键"sv},
    {"Remember Menu Open/Closed State"sv, "记住菜单开关状态"sv},
    {"Enable L3 + R3 Toggle"sv, "启用 L3 + R3 开关菜单"sv},
    {"L3 + R3 Long Press Menu Toggle"sv, "长按 L3 + R3 开关菜单"sv},
    {"Always Show Cursor"sv, "始终显示光标"sv},
    {"Log Level"sv, "日志级别"sv},
    {"Select GUI Theme"sv, "选择界面主题"sv},
    {"Font Size"sv, "字体大小"sv},
    {"Default Dark"sv, "默认深色"sv},
    {"Alternative Dark"sv, "替代深色"sv},
    {"Default Light"sv, "默认浅色"sv},
    {"High Contrast"sv, "高对比度"sv},
    {"Loading..."sv, "正在加载……"sv},
    {"No runtime loaded."sv, "未加载 VR 运行时。"sv},
    {"Attempt to reinitialize"sv, "尝试重新初始化"sv},
    {"Set Standing Height"sv, "设置站立高度"sv},
    {"Set Standing Origin"sv, "设置站立原点"sv},
    {"Recenter View"sv, "重置视角中心"sv},
    {"Recenter Horizon"sv, "重置水平视角"sv},
    {"Reinitialize Runtime"sv, "重新初始化运行时"sv},
    {"%s not loaded: %s not found"sv, "%s 未加载：找不到 %s"sv},
    {"Please select %s from the loader if you want to use %s"sv, "如需使用 %s，请在加载器中选择 %s"sv},
    {"%s not loaded: %s"sv, "%s 未加载：%s"sv},
    {"%s not loaded: Unknown error"sv, "%s 未加载：未知错误"sv},
    {"Render Resolution (per-eye): %d x %d"sv, "渲染分辨率（单眼）：%d x %d"sv},
    {"Total Render Resolution: %d x %d"sv, "总渲染分辨率：%d x %d"sv},
    {"Resolution can be changed in SteamVR"sv, "可在 SteamVR 中更改分辨率"sv},
    {"Desktop Spectator View"sv, "桌面观众视图"sv},
    {"Desktop Spectator Mode"sv, "桌面观战模式"sv},
    {"Desktop Spectator Eye"sv, "桌面观战眼睛"sv},
    {"Desktop Spectator Aspect"sv, "桌面观战宽高比"sv},
    {"Desktop Spectator FOV Override"sv, "启用桌面观战 FOV 自定义"sv},
    {"Desktop Spectator Horizontal FOV"sv, "桌面观战水平视场角"sv},
    {"Cinematic spectator FOV: baseline %.1f, target %.1f, effective %.1f degrees (%s)"sv, "电影级观战 FOV：自动基准 %.1f°，目标 %.1f°，实际 %.1f°（%s）"sv},
    {"Cinematic spectator FOV override unavailable: %s"sv, "电影级观战 FOV 自定义不可用：%s"sv},
    {"Automatic"sv, "自动"sv},
    {"Cropped"sv, "裁切缩放"sv},
    {"Expanded"sv, "扩展投影"sv},
    {"Custom spectator FOV requires the Extreme/AFR Cinematic path"sv, "自定义观战 FOV 仅支持 Extreme/AFR 电影级路径"sv},
    {"Custom spectator FOV currently supports Meta OpenXR only"sv, "自定义观战 FOV 当前仅支持 Meta OpenXR"sv},
    {"Could not solve the requested cropped spectator FOV"sv, "无法求解请求的裁切观战 FOV，已使用自动基准"sv},
    {"Could not solve the requested expanded spectator FOV"sv, "无法求解请求的扩展观战 FOV，已使用自动基准"sv},
    {"Custom spectator FOV requires Cinematic 16:9 mode"sv, "自定义观战 FOV 需要启用电影级 16:9 模式"sv},
    {"Existing Desktop Fix"sv, "现有桌面修复"sv},
    {"Cinematic 16:9"sv, "电影级 16:9"sv},
    {"Left Eye"sv, "左眼"sv},
    {"Right Eye"sv, "右眼"sv},
    {"Cinematic spectator status: %s"sv, "电影级观战状态：%s"sv},
    {"Cinematic spectator eye: %s, effective aspect: %.6f"sv, "电影级观战眼睛：%s，有效宽高比：%.6f"sv},
    {"Cinematic spectator horizontal FOV: %.1f degrees"sv, "电影级观战水平视场角：%.1f 度"sv},
    {"Off"sv, "关闭"sv},
    {"Waiting for OpenXR FOV"sv, "等待 OpenXR 视场角"sv},
    {"Active"sv, "已启用"sv},
    {"Fallback"sv, "已回退"sv},
    {"Cinematic spectator changes require Reinitialize Runtime."sv, "电影级观战设置将在重新初始化运行时后生效。"sv},
    {"Cinematic spectator fallback: %s"sv, "电影级观战已回退：%s"sv},
    {"Cinematic spectator requires Meta OpenXR and D3D11."sv, "电影级观战需要 Meta OpenXR 和 D3D11。"sv},
    {"2D Screen Mode"sv, "二维屏幕模式"sv},
    {"Rendering Method"sv, "渲染方式"sv},
    {"Synced Sequential Method"sv, "同步顺序渲染方式"sv},
    {"World Scale"sv, "世界缩放"sv},
    {"Depth Scale"sv, "深度缩放"sv},
    {"Disable HZBOcclusion"sv, "禁用 HZB 遮挡剔除"sv},
    {"Disable Instance Culling"sv, "禁用实例剔除"sv},
    {"Disable HDR Composition"sv, "禁用 HDR 合成"sv},
    {"Disable Blur Widgets"sv, "禁用模糊控件"sv},
    {"Uncap Framerate"sv, "解除帧率上限"sv},
    {"Enable GUI"sv, "启用游戏界面 (GUI)"sv},
    {"Enable Depth-based Latency Reduction"sv, "启用基于深度的延迟降低"sv},
    {"Load Blueprint Code"sv, "加载蓝图代码"sv},
    {"Ghosting Fix"sv, "重影修复"sv},
    {"Native Stereo Fix"sv, "原生立体渲染修复 (Native Stereo Fix)"sv},
    {"Use Same Stereo Pass"sv, "使用相同立体渲染 Pass"sv},
    {"Near Clip Plane"sv, "近裁剪平面"sv},
    {"Controller"sv, "控制器"sv},
    {"VR Joystick Deadzone"sv, "VR 摇杆死区"sv},
    {"Controller Pitch Offset"sv, "控制器俯仰偏移"sv},
    {"DPad Shifting"sv, "方向键映射"sv},
    {"Left-handed Controller Inputs"sv, "左手模式控制器输入"sv},
    {"DPad Shifting Method"sv, "方向键映射方式"sv},
    {"Aim Method"sv, "瞄准方式"sv},
    {"Some games may not work with this enabled."sv, "启用此项后，部分游戏可能无法正常工作。"sv},
    {"Type"sv, "类型"sv},
    {"Speed"sv, "速度"sv},
    {"Smoothing"sv, "平滑"sv},
    {"Modify Player Control Rotation"sv, "修改玩家控制旋转"sv},
    {"Use Pawn Control Rotation"sv, "使用 Pawn 控制旋转"sv},
    {"Multiplayer Support"sv, "多人游戏支持"sv},
    {"Snap Turn"sv, "快速转向"sv},
    {"Enabled"sv, "启用"sv},
    {"Enable"sv, "启用"sv},
    {"Disable"sv, "禁用"sv},
    {"Angle"sv, "角度"sv},
    {"Deadzone"sv, "死区"sv},
    {"Movement Orientation"sv, "移动方向"sv},
    {"Roomscale Movement"sv, "房间尺度移动"sv},
    {"Sweep Movement"sv, "移动碰撞扫描"sv},
    {"When enabled, headset movement will affect the movement of the player character."sv, "启用后，头显移动将影响玩家角色的移动。"sv},
    {"When enabled, roomscale movement will use a sweep to prevent the player from moving through walls.\nThis also allows physics objects to interact with the player, like doors."sv, "启用后，房间尺度移动会使用碰撞扫描，防止玩家穿墙。\n这也允许门等物理对象与玩家发生交互。"sv},
    {"Camera Freeze"sv, "相机冻结"sv},
    {"Camera Offset"sv, "相机偏移"sv},
    {"Freeze Position"sv, "冻结位置"sv},
    {"Freeze Rotation"sv, "冻结旋转"sv},
    {"Camera Lerp"sv, "相机平滑插值"sv},
    {"Lerp Pitch"sv, "平滑俯仰"sv},
    {"Lerp Yaw"sv, "平滑偏航"sv},
    {"Lerp Roll"sv, "平滑翻滚"sv},
    {"Lerp Speed"sv, "插值速度"sv},
    {"Decoupled Pitch"sv, "独立俯仰"sv},
    {"Auto Adjust UI"sv, "自动调整界面"sv},
    {"Playspace Keys"sv, "游玩空间按键"sv},
    {"Recenter View Key"sv, "重置视角中心按键"sv},
    {"Recenter Horizon Key"sv, "重置水平视角按键"sv},
    {"Set Standing Origin Key"sv, "设置站立原点按键"sv},
    {"Camera Keys"sv, "相机按键"sv},
    {"Load Camera 0 Key"sv, "加载相机 0 按键"sv},
    {"Load Camera 1 Key"sv, "加载相机 1 按键"sv},
    {"Load Camera 2 Key"sv, "加载相机 2 按键"sv},
    {"Overlay/Runtime Keys"sv, "覆盖层/运行时按键"sv},
    {"Toggle 2D Screen Mode Key"sv, "开关二维屏幕模式按键"sv},
    {"Toggle In-Game UI Key"sv, "开关游戏内界面按键"sv},
    {"Disable VR Key"sv, "禁用 VR 按键"sv},
    {"Compatibility Options"sv, "兼容性选项"sv},
    {"AHUD UI Compatibility"sv, "AHUD 界面兼容"sv},
    {"Skip UObjectArray Init"sv, "跳过 UObjectArray 初始化"sv},
    {"Skip PostInitProperties"sv, "跳过 PostInitProperties"sv},
    {"SceneView Compatibility Mode"sv, "SceneView 兼容模式"sv},
    {"Extreme Compatibility Mode"sv, "极限兼容模式"sv},
    {"Horizontal Projection"sv, "水平投影"sv},
    {"Vertical Projection"sv, "垂直投影"sv},
    {"Scale Render Target"sv, "缩放渲染目标"sv},
    {"Splitscreen Compatibility"sv, "分屏兼容"sv},
    {"Index"sv, "索引"sv},
    {"Sync Mode"sv, "同步模式"sv},
    {"Controllers allowed"sv, "允许控制器"sv},
    {"Show FPS"sv, "显示 FPS"sv},
    {"Show Engine Statistics"sv, "显示引擎统计信息"sv},
    {"Native Stereo"sv, "原生立体渲染 (Native Stereo)"sv},
    {"Synchronized Sequential"sv, "同步顺序渲染 (Synchronized Sequential)"sv},
    {"Alternating/AFR"sv, "交替帧渲染 (AFR)"sv},
    {"Early"sv, "提前"sv},
    {"Late"sv, "延后"sv},
    {"Very Late"sv, "大幅延后"sv},
    {"Skip Tick"sv, "跳过 Tick"sv},
    {"Skip Draw"sv, "跳过 Draw"sv},
    {"Game"sv, "游戏"sv},
    {"Head/HMD"sv, "头部/头显"sv},
    {"Right Controller"sv, "右控制器"sv},
    {"Left Controller"sv, "左控制器"sv},
    {"Two Handed (Right)"sv, "双手（右手主导）"sv},
    {"Two Handed (Left)"sv, "双手（左手主导）"sv},
    {"Right Thumbrest + Left Joystick"sv, "右拇指托 + 左摇杆"sv},
    {"Left Thumbrest + Right Joystick"sv, "左拇指托 + 右摇杆"sv},
    {"Left Joystick (Disables Standard Joystick Input)"sv, "左摇杆（禁用标准摇杆输入）"sv},
    {"Right Joystick (Disables Standard Joystick Input)"sv, "右摇杆（禁用标准摇杆输入）"sv},
    {"Gesture (Head) + Left Joystick"sv, "头部手势 + 左摇杆"sv},
    {"Gesture (Head) + Right Joystick"sv, "头部手势 + 右摇杆"sv},
    {"Raw / default"sv, "原始/默认"sv},
    {"Symmetrical"sv, "对称"sv},
    {"Mirrored"sv, "镜像"sv},
    {"Matched"sv, "匹配"sv},
    {"Waiting for UObjectBase to be hooked..."sv, "正在等待 UObjectBase Hook……"sv},
    {"UObjectHook is disabled"sv, "UObjectHook 已禁用"sv},
    {"Re-enable"sv, "重新启用"sv},
    {"Reload Persistent States"sv, "重新加载持久状态"sv},
    {"Destroy Persistent States"sv, "销毁持久状态"sv},
    {"Enabled at Startup"sv, "启动时启用"sv},
    {"Enable Attach Lerp"sv, "启用附加平滑插值"sv},
    {"Attach Lerp Speed"sv, "附加插值速度"sv},
    {"UObjectHook Keybinds"sv, "UObjectHook 按键绑定"sv},
    {"Disable UObjectHook Key"sv, "禁用 UObjectHook 按键"sv},
    {"Dump SDK"sv, "导出 SDK"sv},
    {"Debug Stats"sv, "调试统计"sv},
    {"Constructor calls: %llu"sv, "构造调用：%llu"sv},
    {"Destructor calls: %llu"sv, "析构调用：%llu"sv},
    {"Create ProcessEvent hook"sv, "创建 ProcessEvent Hook"sv},
    {"ProcessEvent Listener"sv, "ProcessEvent 监听器"sv},
    {"Clear Ignored Functions"sv, "清除已忽略函数"sv},
    {"Clear Called Functions"sv, "清除已调用函数"sv},
    {"Ignore All Called Functions"sv, "忽略全部已调用函数"sv},
    {"Called functions: %llu"sv, "已调用函数：%llu"sv},
    {"Recent Functions"sv, "最近函数"sv},
    {"All Called Functions"sv, "全部已调用函数"sv},
    {"Ignore"sv, "忽略"sv},
    {"Max Calls"sv, "最大调用数"sv},
    {"Search"sv, "搜索"sv},
    {"Failed to hook ProcessEvent!"sv, "ProcessEvent Hook 失败！"sv},
    {"Address Lookup"sv, "地址查询"sv},
    {"Attached Components"sv, "已附加组件"sv},
    {"Detach all"sv, "全部分离"sv},
    {"Attached Camera Object"sv, "已附加相机对象"sv},
    {"Detach Camera"sv, "分离相机"sv},
    {"Spawn Overlapper"sv, "创建重叠检测器"sv},
    {"Overlapped Objects"sv, "重叠对象"sv},
    {"Destroy Overlapper"sv, "销毁重叠检测器"sv},
    {"Attach all"sv, "全部附加"sv},
    {"Objects: %zu (%zu actual)"sv, "对象：%zu（实际 %zu）"sv},
    {"Recent Objects"sv, "最近对象"sv},
    {"Common Objects"sv, "常用对象"sv},
    {"PlayerController"sv, "PlayerController"sv},
    {"No player controller"sv, "无 PlayerController"sv},
    {"Acknowledged Pawn"sv, "已确认 Pawn"sv},
    {"No pawn"sv, "无 Pawn"sv},
    {"Camera Manager"sv, "相机管理器"sv},
    {"No camera manager"sv, "无相机管理器"sv},
    {"World"sv, "世界"sv},
    {"No world"sv, "无 World"sv},
    {"Objects by class"sv, "按类查看对象"sv},
    {"Hide Default Classes"sv, "隐藏默认类"sv},
    {"Filter"sv, "筛选"sv},
    {"Add Component Permanently"sv, "永久添加组件"sv},
    {"Copy Name"sv, "复制名称"sv},
    {"Copy Address"sv, "复制地址"sv},
    {"Invalid object"sv, "无效对象"sv},
    {"null class"sv, "空类"sv},
    {"Invalid class"sv, "无效类"sv},
    {"Default Object"sv, "默认对象"sv},
    {"Null default object"sv, "默认对象为空"sv},
    {"Outer"sv, "外层对象 (Outer)"sv},
    {"Set to Screen Space"sv, "设为屏幕空间"sv},
    {"Destroy Component"sv, "销毁组件"sv},
    {"Detach"sv, "分离"sv},
    {"Adjust"sv, "调整"sv},
    {"Permanent Change"sv, "永久更改"sv},
    {"RotationOffset"sv, "旋转偏移"sv},
    {"PositionOffset"sv, "位置偏移"sv},
    {"Save state"sv, "保存状态"sv},
    {"Can't save, did not start from a valid base or none of the allowed bases can reach this component"sv, "无法保存：起点不是有效基准，或允许的基准均无法访问此组件"sv},
    {"Can't save, did not start from a valid base or none of the allowed bases can reach this object"sv, "无法保存：起点不是有效基准，或允许的基准均无法访问此对象"sv},
    {"Can't save, did not start from a valid base"sv, "无法保存：起点不是有效基准"sv},
    {"Attach left"sv, "附加到左手"sv},
    {"Attach right"sv, "附加到右手"sv},
    {"Attach HMD"sv, "附加到头显"sv},
    {"Attach Camera to"sv, "将相机附加到此对象"sv},
    {"Attach Camera to (Relative)"sv, "将相机相对附加到此对象"sv},
    {"Visible"sv, "可见"sv},
    {"Save Visibility State"sv, "保存可见性状态"sv},
    {"Sockets"sv, "插槽 (Socket)"sv},
    {"Components"sv, "组件"sv},
    {"Properties"sv, "属性"sv},
    {"Functions"sv, "函数"sv},
    {"Inheritance"sv, "继承关系"sv},
    {"Add Component"sv, "添加组件"sv},
    {"Apply to all actors"sv, "应用到全部 Actor"sv},
    {"Call"sv, "调用"sv},
    {"Save Property"sv, "保存属性"sv},
    {"Unsave Property"sv, "取消保存属性"sv},
    {"Cannot determine struct size"sv, "无法确定结构体大小"sv},
    {"Cannot determine struct type"sv, "无法确定结构体类型"sv},
    {"Failed to get inner property"sv, "无法获取内部属性"sv},
    {"Failed to get inner property class"sv, "无法获取内部属性类"sv},
    {"Empty array"sv, "空数组"sv},
    {"Array of %s (unsupported)"sv, "%s 数组（不支持）"sv},
    {"Failed to display element %d"sv, "无法显示元素 %d"sv},
    {"Page: %d"sv, "页码：%d"sv},
    {"Attempt Unload Plugins"sv, "尝试卸载插件"sv},
    {"Reload Plugins"sv, "重新加载插件"sv},
    {"Loaded plugins:"sv, "已加载插件："sv},
    {"No plugins loaded."sv, "未加载插件。"sv},
    {"Errors:"sv, "错误："sv},
    {"Warnings:"sv, "警告："sv},
    {"Run script"sv, "运行脚本"sv},
    {"Reset scripts"sv, "重置脚本"sv},
    {"Spawn Debug Console"sv, "打开调试控制台"sv},
    {"Garbage Collection Stats"sv, "垃圾回收统计"sv},
    {"Megabytes in use: %.2f"sv, "已用内存（MB）：%.2f"sv},
    {"Garbage Collection Handler"sv, "垃圾回收管理方"sv},
    {"Garbage Collection Mode"sv, "垃圾回收模式"sv},
    {"Minor GC Multiplier"sv, "次要 GC 倍率"sv},
    {"Major GC Multiplier"sv, "主要 GC 倍率"sv},
    {"Garbage Collection Type"sv, "垃圾回收类型"sv},
    {"Garbage Collection Budget"sv, "垃圾回收预算"sv},
    {"Log Lua Errors to Disk"sv, "将 Lua 错误写入磁盘"sv},
    {"Last Error Time: %.2f seconds ago"sv, "最后错误时间：%.2f 秒前"sv},
    {"Last Script Error: %s"sv, "最后脚本错误：%s"sv},
    {"No Script Errors... yet!"sv, "目前没有脚本错误。"sv},
    {"Known scripts:"sv, "已知脚本："sv},
    {"No scripts loaded."sv, "未加载脚本。"sv},
    {"Managed by UEVR"sv, "由 UEVR 管理"sv},
    {"Managed by Lua"sv, "由 Lua 管理"sv},
    {"Step"sv, "分步"sv},
    {"Full"sv, "完整"sv},
    {"Generational"sv, "分代式"sv},
    {"Incremental (Mark & Sweep)"sv, "增量式（标记与清除）"sv},
    {"CVars"sv, "控制台变量 (CVar)"sv},
    {"UEVR Console"sv, "UEVR 控制台"sv},
    {"Note: Any changes here will be frozen."sv, "注意：此处的任何更改都会被锁定。"sv},
    {"Frozen CVars: %i"sv, "已锁定 CVar：%i"sv},
    {"Display Console"sv, "显示控制台"sv},
    {"Spawn Native Console"sv, "打开原生控制台"sv},
    {"Dump All CVars"sv, "导出全部 CVar"sv},
    {"Clear Frozen CVars"sv, "清除已锁定 CVar"sv},
    {"Failed to get FConsoleManager."sv, "无法获取 FConsoleManager。"sv},
    {"Note: This is a homebrew console. It is not the same as the in-game console."sv, "注意：这是 UEVR 自制控制台，与游戏内控制台不同。"sv},
    {"Failed to find cvar: %s"sv, "找不到 CVar：%s"sv},
    {"Unimplemented cvar type: %s"sv, "未实现的 CVar 类型：%s"sv},
    {"Failed to read cvar: %s"sv, "读取 CVar 失败：%s"sv},
    {"Failed to find cvar data: %s"sv, "找不到 CVar 数据：%s"sv},
    {"Failed to read cvar data: %s"sv, "读取 CVar 数据失败：%s"sv},
    {"Stereo Hook Options"sv, "立体渲染 Hook 选项"sv},
    {"Asynchronous Code Scanning"sv, "异步代码扫描"sv},
    {"Recreate Textures on Reset"sv, "重置时重建纹理"sv},
    {"Frame Delay Compensation"sv, "帧延迟补偿"sv},
    {"Use FMalloc for ISceneViewExtensions"sv, "为 ISceneViewExtensions 使用 FMalloc"sv},
    {"Spawn scene capture"sv, "创建场景捕获"sv},
    {"Destroy scene capture"sv, "销毁场景捕获"sv},
    {"Create texture"sv, "创建纹理"sv},
    {"Destroy texture"sv, "销毁纹理"sv},
    {"Scene Capture Texture: %s"sv, "场景捕获纹理：%s"sv},
    {"GetRenderTargetTexture Retaddrs"sv, "GetRenderTargetTexture 返回地址"sv},
    {"Call Original"sv, "调用原函数"sv},
    {"Redirect"sv, "重定向"sv},
    {"[Calling Original]"sv, "【调用原函数】"sv},
    {"[Redirected]"sv, "【已重定向】"sv},
    {"[Default]"sv, "【默认】"sv},
    {"Overlay Options"sv, "覆盖层选项"sv},
    {"Overlay Type"sv, "覆盖层类型"sv},
    {"UI Cylinder Angle"sv, "界面圆柱角度"sv},
    {"UI Offset"sv, "界面偏移"sv},
    {"UI Distance"sv, "界面距离"sv},
    {"HUD Horizontal Position"sv, "HUD 左右位置"sv},
    {"HUD Vertical Position"sv, "HUD 上下位置"sv},
    {"HUD Distance"sv, "HUD 距离"sv},
    {"Reset HUD Position"sv, "重置 HUD 位置"sv},
    {"UI Size"sv, "界面大小"sv},
    {"UI Follows View"sv, "界面跟随视角"sv},
    {"UI Invert Alpha"sv, "界面反转透明度"sv},
    {"Framework Distance"sv, "框架界面距离"sv},
    {"Framework Size"sv, "框架界面大小"sv},
    {"Framework Follows View"sv, "框架界面跟随视角"sv},
    {"Framework Wrist UI"sv, "框架腕部界面"sv},
    {"Framework Mouse Emulation"sv, "框架鼠标模拟"sv},
    {"OpenXR Options"sv, "OpenXR 选项"sv},
    {"Resolution Scale"sv, "分辨率缩放"sv},
    {"Virtual Desktop Fix"sv, "Virtual Desktop 修复"sv},
    {"Ignore Virtual Desktop Checks"sv, "忽略 Virtual Desktop 检查"sv},
    {"Bindings"sv, "绑定"sv},
    {"Interaction Profile: %s"sv, "交互配置：%s"sv},
    {"Restore Default Bindings"sv, "恢复默认绑定"sv},
    {"Save Bindings"sv, "保存绑定"sv},
    {"Interaction profile not loaded, try putting on your headset."sv, "尚未加载交互配置，请尝试戴上头显。"sv},
    {"New Binding (e.g. /user/hand/left/input/trigger)"sv, "新绑定（例如 /user/hand/left/input/trigger）"sv},
    {"Action"sv, "动作"sv},
    {"Add Binding"sv, "添加绑定"sv},
    {"Vector2 Associations"sv, "Vector2 关联"sv},
    {"Value"sv, "数值"sv},
    {"Command"sv, "命令"sv},
    {"Description"sv, "说明"sv},
    {"Insert New Output"sv, "插入新输出"sv},
    {"New Vector2 Activator"sv, "新 Vector2 激活器"sv},
    {"New Vector2 Modifier"sv, "新 Vector2 修改器"sv},
    {"New Vector2 Output"sv, "新 Vector2 输出"sv},
    {"New Vector2 Value"sv, "新 Vector2 数值"sv},
    {"Add Vector2 Association"sv, "添加 Vector2 关联"sv},
    {"Unknown page selected"sv, "选择了未知页面"sv},
    {"WARNING: Hardware-accelerated GPU scheduling is enabled. This may cause the game to run slower."sv, "警告：已启用硬件加速 GPU 计划，这可能导致游戏运行变慢。"sv},
    {"Go into your Windows Graphics settings and disable \"Hardware-accelerated GPU scheduling\""sv, "请前往 Windows 图形设置，关闭“硬件加速 GPU 计划”。"sv},
    {"Note: This is only necessary if you are experiencing performance issues."sv, "注意：仅在遇到性能问题时才需要这样做。"sv},
    {"WARNING: DLSS Frame Generation has been detected. Make sure it is disabled within in-game settings."sv, "警告：检测到 DLSS 帧生成，请确认已在游戏设置中关闭。"sv},
    {"Runtime Information (%s)"sv, "运行时信息（%s）"sv},
    {"Save Camera"sv, "保存相机"sv},
    {"Load Camera"sv, "加载相机"sv},
    {"Hardware scheduling: %s"sv, "硬件 GPU 计划：%s"sv},
    {"Disabled"sv, "禁用"sv},
    {"Right Bounds"sv, "右眼边界"sv},
    {"Left Bounds"sv, "左眼边界"sv},
    {"Disable Projection Matrix Override"sv, "禁用投影矩阵覆盖"sv},
    {"Disable View Matrix Override"sv, "禁用视图矩阵覆盖"sv},
    {"Disable Backbuffer Size Override"sv, "禁用后备缓冲区尺寸覆盖"sv},
    {"Disable VR Overlay"sv, "禁用 VR 覆盖层"sv},
    {"Disable VR Entirely"sv, "完全禁用 VR"sv},
    {"Stereo Emulation Mode"sv, "立体渲染模拟模式"sv},
    {"Wait for Present"sv, "等待 Present"sv},
    {"Controller test mode"sv, "控制器测试模式"sv},
    {"Prediction Scale"sv, "预测缩放"sv},
    {"Raw Left"sv, "左眼原始值"sv},
    {"Raw Right"sv, "右眼原始值"sv},
    {"Left Stick"sv, "左摇杆"sv},
    {"Right Stick"sv, "右摇杆"sv},
    {"AimMethod Notification"sv, "瞄准方式提示"sv},
    {"Continue holding down L3 + R3 to toggle aim method"sv, "继续按住 L3 + R3 以切换瞄准方式"sv},
    {"RT Modifier Controls"sv, "RT 组合键控制"sv},
    {"RT + Left Stick: Camera left/right/forward/back"sv, "RT + 左摇杆：相机左移/右移/前移/后移"sv},
    {"RT + Right Stick: Camera up/down"sv, "RT + 右摇杆：相机上移/下移"sv},
    {"DPad Left: Previous page | DPad Right: Next page"sv, "方向键左：上一页 | 方向键右：下一页"sv},
    {"RT + B: Save Camera 2"sv, "RT + B：保存相机 2"sv},
    {"RT + Y: Save Camera 1"sv, "RT + Y：保存相机 1"sv},
    {"RT + X: Save Camera 0"sv, "RT + X：保存相机 0"sv},
    {"RT + B: Load Camera 2"sv, "RT + B：加载相机 2"sv},
    {"RT + Y: Load Camera 1"sv, "RT + Y：加载相机 1"sv},
    {"RT + X: Load Camera 0"sv, "RT + X：加载相机 0"sv},
    {"RT + B: Reset camera offset"sv, "RT + B：重置相机偏移"sv},
    {"RT + Y: Recenter view"sv, "RT + Y：重置视角中心"sv},
    {"RT + X: Reset standing origin"sv, "RT + X：重置站立原点"sv},
    {"Legacy"sv, "旧版"sv},
    {"Location"sv, "位置"sv},
    {"Rotation"sv, "旋转"sv},
    {"nullptr"sv, "空指针 (nullptr)"sv},
    {"[empty string]"sv, "【空字符串】"sv},
    {"[Called]"sv, "【已调用】"sv},
    {"[Out]"sv, "【输出】"sv},
    {"Apply"sv, "应用"sv},
    {"Continue"sv, "继续"sv},
    {"Close"sv, "关闭"sv},
    {"Cancel"sv, "取消"sv},
    {"Unknown"sv, "未知"sv},
    {"Exists"sv, "存在"sv},
    {"Does not exist"sv, "不存在"sv},
};

} // namespace

Language get_language() {
    return g_language.load(std::memory_order_relaxed);
}

void set_language(Language language) {
    g_language.store(language == Language::EN_US ? Language::EN_US : Language::ZH_CN, std::memory_order_relaxed);
}

void set_language(int32_t language) {
    set_language(language == static_cast<int32_t>(Language::EN_US) ? Language::EN_US : Language::ZH_CN);
}

const char* get(const char* english_text) {
    if (english_text == nullptr || get_language() == Language::EN_US) {
        return english_text;
    }

    const auto it = ZH_CN.find(english_text);
    return it != ZH_CN.end() ? it->second.data() : english_text;
}

const char* get_zh_cn_glyph_text() {
    static const std::string glyph_text = []() {
        std::string result{};
        for (const auto& [_, translation] : ZH_CN) {
            result.append(translation);
        }
        return result;
    }();

    return glyph_text.c_str();
}

} // namespace localization
